config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:index, :new, :create]

  root "orders#index"
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :buyer, :address, :supplier, :unit_price, :quantity, :description, :presence => true
  
  before_create :set_total_price
  
  def self.create_from(data)
    buyer, description, unit_price, quantity, address, supplier = data.split("\t").map do |attribute|
      normalize(attribute)
    end
    
    Order.create({
      :buyer       => buyer, 
      :description => description,
      :unit_price  => unit_price.to_f,
      :quantity    => quantity.to_i, 
      :address     => address, 
      :supplier    => supplier
    })
  end
  
  private
    
    def set_total_price
      self.total_price = self.unit_price * self.quantity
    end
    
    def self.normalize(attribute)
      if attribute.encoding.name == "ASCII-8BIT" 
        attribute.encode("ASCII-8BIT").force_encoding("UTF-8")
      else
        attribute.force_encoding("UTF-8")
      end
    end
    
    private_class_method :normalize
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper
  
  def index
    order_by = permitted_params[:order_by] || :id
    @sorting = permitted_params[:sorting] || :asc 
    @orders  = Order.all.order(order_by => @sorting)
    @total   = @orders.sum(:total_price)
  end
  
  def new
  end
  
  def create
    parse(permitted_params[:uploaded_file])

    redirect_to orders_path
  end
  
  private
  
    def permitted_params
      params.permit(:uploaded_file, :order_by, :sorting)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_sort_by(table, field, sorting) 
    link_to t("#{table}.#{field}"), orders_path({ :order_by => field, :sorting => reverse(sorting) })
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def parse(raw_file)
    data = raw_file.try(:read)
    return unless data

    data.each_line do |row|
      Order.create_from(row) unless row.include?("Comprador")
    end
  end
  
  def reverse(sorting)
    sorting.to_sym == :asc ? :desc : :asc
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pedidos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<h1>Pedidos</h1>
<% unless @orders.empty? %>
<table class="ordersTable">
  <thead>
    <tr>
      <th><%= link_sort_by(:order, :buyer, @sorting) %></th>
      <th><%= t("order.description") %></th>
      <th><%= t("order.unit_price") %></th>
      <th><%= t("order.quantity") %></th>
      <th><%= link_sort_by(:order, :total_price, @sorting) %></th>
      <th><%= t("order.address") %></th>
      <th><%= link_sort_by(:order, :supplier, @sorting) %></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    <tr class="<%= cycle("odd", "even") %>">
      <td><%= order.buyer %></td>
      <td><%= order.description %></td>
      <td><%= number_to_currency(order.unit_price) %></td>
      <td><%= order.quantity %></td>
      <td><%= number_to_currency(order.total_price) %></td>
      <td><%= order.address %></td>
      <td><%= order.supplier %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr class="total">
      <th><%= t('view.order.total')%></th>
      <td><%= number_to_currency(@total) %></td>
    </tr>
  </tfoot>
</table>
<br>
<% end %>
<%= link_to t("view.order.import"), new_order_path %>

app/views/orders/new.html.erb
<h1>Importar novo arquivo</h1>

<%= form_tag orders_path, :method => "post", :multipart => true do %>
<%= file_field_tag :uploaded_file %>
<br>
<br>
<%= submit_tag t("view.order.send") %>
<% end %>